# SPDX-FileCopyrightText: 2023 Konrad Borowski <konrad@borowski.pw>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

when:
  - event: pull_request
  - event: push
    branch:
       - master

steps:
  rustfmt:
    image: rust
    commands:
      - rustup component add rustfmt
      - cargo fmt --check
