# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

when:
  - event: pull_request
  - event: push
    branch:
       - master

matrix:
  RUST_IMAGE:
    - rust
<<<<<<< HEAD
    - "rust:1.61"
=======
    - "rust:1.66"
>>>>>>> 5558906 (Add optional support for `borsh` serialisation)

steps:
  test:
    image: ${RUST_IMAGE}
    environment:
      - CARGO_TERM_COLOR=always
    commands:
      - cargo build --all-features --locked --verbose
      - cargo test --all-features --locked --verbose
